### ISSUE TITLE
Erlang Elixir support

### ISSUE THREAD

**Issue by nicobao** [vaclav/mpscs#6]
Hi,

Thanks for your work on MPS.
I wonder how much resources (engineering time/people) it took you to add support for C#? I am still new to language workbenchs but I am interested in adding support for Erlang/Elixir - myself. Is that even feasible?

If I understand well that would enable us to prettyprint valid Erlang/Elixir programs directly from Jetbrains MPS Generators?
Is there any alternative solutions right now for working with Erlang/Elixir from MPS-based DSL?

With kind regards,
Nicolas

EDIT: also something I don't understand yet, is how do you make sure the generated C# code is valid?
For Java it is easy as MPS itself is written in Java but what about external languages? How do you make sure you implemented the grammar of the language correctly?
Also, how do you add support for non-standard librairies of C#?

**Comment by wirthma** [comment]
Hey NicoGim,

thank you for your interest in this project.

### Time resources

This project was implemented as a school team project at a university. The team had 5 members and we worked on it approximately 9 months. However, not full-time. I guess it might have took us approximately 2 months of full-time work (meaning 5 days a week). Therefore, for one person, it would be definitely a matter of a half a year or more, full-time.

However, we implemented or extended several reusable MPS plugins that automate or ease some parts of base language development. For example, you can get the TextGen aspect by a few clicks from the Editor aspect or development of the support of standard libraries for the language should be simpler with our plugins.

Also, there is no need to implement all features of the language (neither did we implement the latest C# features). You can implement only the most important parts of the language that are required for simple programs. Actually, implementing the language core is quite fast, you may get it in a week or a few weeks.

The most of the work is getting the language user-friendly, i.e. improving the editors (e.g. not to show empty cells of inheritance in the editor when a class does not inherit anything) and implement various transformation actions (e.g. adding a plus to a number means creation of a sum operator and a cell of the other number).

Furthermore, even though we made development of the support for standard libraries easier, it will take you a considerable amount of time.

I am not familiar with Erlang/Elixir much but a very rough guess would be a few months long full-time work for one person.

### Erlang/Elixir programs directly from MPS

Providing you would implement Erlang/Elixir in MPS, it would allow you to pretty-print valid Erlang/Elixir programs directly from MPS. It would also allow you to use Erlang/Elixir from your DSLs and it would enable you to quite easily extend Erlang/Elixir for example by some your innovative constructs or features.

### Validity of code

The validity of code is ensured by correctly implementing the language parts in MPS. There is no mathematical proof that the language implementation is correct but you may test it by writing example programs. That is what we did. We took the official C# 5.0 grammar, implemented the MPS C# base language according to that and tested that our example C# programs can be coded in our MPS language and then that they can be correctly transformed into text source code.

### Non-standard libraries

This is a little complicated as non standard libraries have dependencies on other libraries (typically at least on the standard library). We did not implement automatic support for this. Not that it is impossible but unfortunately we did not have time for this. Therefore, you must manually assist the process when generating MPS stubs for other than standard libraries and it is quite ugly thing (but possible).

### Alternative solution for Erlang/Elixir implementation in MPS

You do not have to implement Erlang/Elixir as an MPS base language but as if it was just another DSL implemented in MPS. This would give you more support from the MPS team in case of problems or it would provide you with better documentation (because implementing a DSL is a standard functionality of MPS while implementing a base language is something only several people did). However, the amount of work is quite comparable in both the two scenarios.

As for some other alternative solutions for working with Erlang/Elixir from MPS-based DSL, I am not the right person to answer that. @vaclav is the most MPS-aware person here.
